apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
  namespace: retail-app
  labels:
    app: assets
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
        version: v1
    spec:
      serviceAccountName: default
      containers:
      - name: assets
        image: public.ecr.aws/aws-containers/retail-store-sample-assets:0.8.5
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
