apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: retail-app
  labels:
    app: ui
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
        version: v1
    spec:
      serviceAccountName: default
      containers:
      - name: ui
        image: public.ecr.aws/aws-containers/retail-store-sample-ui:1.6.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: retail-app-config
              key: AWS_REGION
        - name: RETAIL_UI_ENDPOINTS_CATALOG
          valueFrom:
            configMapKeyRef:
              name: retail-app-config
              key: RETAIL_UI_ENDPOINTS_CATALOG
        - name: RETAIL_UI_ENDPOINTS_ORDERS
          valueFrom:
            configMapKeyRef:
              name: retail-app-config
              key: RETAIL_UI_ENDPOINTS_ORDERS
        - name: RETAIL_UI_ENDPOINTS_CARTS
          valueFrom:
            configMapKeyRef:
              name: retail-app-config
              key: RETAIL_UI_ENDPOINTS_CARTS
        - name: RETAIL_UI_ENDPOINTS_CHECKOUT
          valueFrom:
            configMapKeyRef:
              name: retail-app-config
              key: RETAIL_UI_ENDPOINTS_CHECKOUT
        - name: RETAIL_UI_ENDPOINTS_ASSETS
          valueFrom:
            configMapKeyRef:
              name: retail-app-config
              key: RETAIL_UI_ENDPOINTS_ASSETS
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
